name: easydev
description: "backend+frontend prototype project"
publish_to: 'none'

version: 1.1.1+116

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  camera: ^0.11.1
  image: ^4.1.3
  fl_chart: ^0.66.2

  # SQLite 패키지
  sqflite: ^2.4.2
  path: ^1.9.1

  # 날짜/시간 형식 변환 패키지
  intl: ^0.20.2
  timezone: ^0.10.1

  # Firebase 관련 패키지
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6

  # 로컬 데이터 및 알림 관련
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.3.0

  # ✅ GCS 업로드 관련 추가
  http: ^1.2.0
  googleapis: ^13.0.0
  googleapis_auth: ^1.6.0
  google_sign_in: ^7.2.0
  extension_google_sign_in_as_googleapis_auth: ^3.0.0
  mime: ^2.0.0
  # Excel 관련 추가
  excel: ^4.0.6

  # Excel&GCS
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  collection: ^1.19.1

  # TTS
  flutter_tts: ^4.2.3
  flutter_foreground_task: ^9.1.0

  url_launcher: ^6.3.1

  # File Export
  share_plus: ^11.0.0
  android_intent_plus: ^5.3.0

  # Calendar&Task
  table_calendar: ^3.2.0

  # QR
  qr_flutter: ^4.1.0

  # git
  flutter_secure_storage: ^9.2.4
  flutter_markdown: ^0.7.7+1

  crypto: ^3.0.6

  google_mlkit_text_recognition: ^0.15.0

  uuid: ^4.5.1

  # video
  video_player: ^2.10.0
  chewie: ^1.13.0
  video_thumbnail: ^0.5.6

  # PDF For Send Mail
  pdf: ^3.11.3
  pdfx: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/pelican_logo.png
    - assets/images/pelican.png
    - assets/images/easyvalet_logo.png
    - assets/images/easyvalet_logo_car.png
    - assets/images/move_to_tablet.png
    - assets/images/move_to_service.png
    - assets/icons/icon_belivussnc.PNG
    - assets/icons/icon_easyvalet.PNG
    - assets/icons/app_icon.png
    - assets/icons/app_icon_ios.png
    - assets/tutorials/
    # ⬇⬇⬇ PDF 전용 폰트 자원(디렉터리 전체 포함)
    - assets/fonts/NotoSansKR/
    - assets/00.basic.pdf

# ↓↓↓ 최상위 레벨 설정 블록 (dev_dependencies 밖)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icons/app_icon.png
  remove_alpha_ios: true
